application: XXX
module: buggy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: ssl
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest

# env_variables:
#   GOOGLE_CLOUD_DISABLE_GRPC: true
